# taps
tap "homebrew/bundle", "https://github.com/Homebrew/homebrew-bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services", "https://github.com/Homebrew/homebrew-services"
tap "beeftornado/rmtree"
tap "eth-p/software"
tap "fabianishere/personal"
tap "jjuarez/tap-1"
tap "nodenv/nodenv"
tap "rahuliyer95/personal"
tap "rbenv/tap"

# brew
brew "ansifilter"
brew "antibody"
brew "automake"
brew "bash"
brew "bash-completion"
brew "beeftornado/rmtree/brew-rmtree"
brew "blueutil"
brew "bottom"
brew "brotli"
brew "bzip2"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "dive"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "duf"
brew "dust"
brew "eth-p/software/bat-extras-batdiff"
brew "eth-p/software/bat-extras-batgrep"
brew "eth-p/software/bat-extras-batman"
brew "eth-p/software/bat-extras-batpipe"
brew "eth-p/software/bat-extras-batwatch"
brew "eth-p/software/bat-extras-prettybat", args: ["ignore-dependencies"]
# brew "ffmpeg"
brew "findutils"
brew "fx", args: ["ignore-dependencies"]
brew "gawk"
# brew "ghostscript"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "goenv"
brew "highlight"
brew "htop"
# brew "java11" unless system "/usr/libexec/java_home failfast"
brew "jq"
brew "known_hosts"
brew "libtool"
brew "libvterm"
brew "lsd"
brew "maven", args: ["ignore-dependencies"]
brew "moreutils"
brew "neovim"
brew "nodenv"
brew "nodenv/nodenv/nodenv-aliases"
brew "nodenv/nodenv/nodenv-update"
brew "pam-reattach"
brew "pandoc"
brew "pinentry-mac"
brew "pkg-config"
brew "pkl"
brew "pyenv"
brew "pyenv-pip-migrate"
brew "rahuliyer95/personal/pam_watchid"
brew "rbenv"
brew "readline"
brew "rlwrap"
brew "shellcheck"
brew "tmux"
brew "vale"
brew "watch"
brew "wget"
brew "xcbeautify"
brew "yarn", args: ["ignore-dependencies"]
brew "yq"
brew "zsh"
brew "zstd"

# cask
cask "1password-beta"
cask "alfred"
cask "android-file-transfer"
cask "dash"
cask "dropbox"
cask "font-fira-code-nerd-font"
cask "font-monaspace-nerd-font"
cask "kap"
cask "keka"
cask "kekaexternalhelper"
cask "kitty"
cask "microsoft-edge"
cask "monitorcontrol"
cask "notion"
cask "qlimagesize"
cask "qlmarkdown"
# cask "qlstephen"
cask "quicklook-json"
cask "scroll-reverser"
cask "shortcutdetective"
cask "suspicious-package"
cask "syntax-highlight"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "yubico-yubikey-personalization-gui"
cask "zoom"
