agent_notes = true
copy_decorations = false
cursor_line = "row"
exclude_untracked = false
hunk_headers = true
line_numbers = true
menu_bar = true
mode = "auto"
tab_width = 2
theme = "tokyo-night"
transparent_background = true
watch = false
wrap_lines = false
